### ISSUE TITLE
NOTE in local check

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/shinywqg#54]
```
N  checking R code for possible problems (3.6s)
   gt_table: no visible binding for global variable ‘Guideline’
   process_limits: no visible binding for global variable ‘.’
   Undefined global functions or variables:
     . Guideline
```

**Comment by sebdalgarno** [comment]
yes this is because I can't use the normal rlang::.data in gt::vars()
I will look into it and see if easy fix

**Comment by sebdalgarno** [comment]
resolved "." by adding `utils::globalVariables(c("."))`
resolved Guideline by 
`locations = gt::cells_data( columns = "Guideline")`
 instead of 
`locations = gt::cells_data( columns = gt::vars(Guideline))`
